const ERRORS = {
  ERROR: 'ERROR',
  CLEAR_ERROR: 'CLEAR_ERROR'
}

const ACCOUNT = {
  REGISTER: 'ACCOUNT_REGISTER',
  AUTHENTICATED: 'ACCOUNT_AUTHENTICATED',
  LOGOUT: 'ACCOUNT_LOGOUT'
}

export { ERRORS, ACCOUNT }